trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  projectName: "dotnetcore-workerservice"
  projectFile: 'dotnetcore-workerservice.csproj'
  projectSolutionFileName: "dotnetcore-workerservice.sln"
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: StageBuild
    displayName: Build
    jobs:
      - job: JobBuildCode
        displayName: Build Code
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget
          - task: NuGetCommand@2
            displayName: Restore Nuget
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
          - task: SonarQubePrepare@5
            displayName: SonarQube - Prepare
            inputs:
              SonarQube: 'SonarQube-GitHub'
              scannerMode: 'MSBuild'
              projectKey: 'GitHub-Project_GitHub-Project'
              projectName: 'GitHub-Project'
          - task: DotNetCoreCLI@2
            displayName: Task - Build Code
            inputs:
              command: 'build'
              projects: '$(projectFile)'
              arguments: --configuration '$(buildConfiguration)'
          - task: SonarQubeAnalyze@5
            displayName: Task - SonarQube - Analysis Start
          - task: SonarQubePublish@5
            displayName: Task - SonarQube - Publish Analysis
            inputs:
              pollingTimeoutSec: '600'